# Generated by Django 6.0.6 on 2026-06-12 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_telegrammessage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="telegrammessage",
            old_name="username",
            new_name="tg_login",
        ),
    ]
