# Generated by Django 6.0.6 on 2026-06-12 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_username_telegrammessage_tg_login"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegrammessage",
            name="chat_id",
        ),
    ]
