# Generated by Django 6.0.6 on 2026-06-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_telegrammessage_chat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegrammessage",
            name="text",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="telegrammessage",
            name="tg_login",
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
