# Generated by Django 6.0.6 on 2026-06-12 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_telegrammessage_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegrammessage",
            name="tg_login",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
