# Generated by Django 6.0.6 on 2026-06-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_telegrammessage_tg_login"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegrammessage",
            name="text",
        ),
        migrations.AddField(
            model_name="telegrammessage",
            name="chatbot_respond",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="telegrammessage",
            name="user_text",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
