from django.contrib.auth import authenticate
from rest_framework import status, viewsets
from rest_framework.authtoken.models import Token
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.response import Response
from django.shortcuts import render, HttpResponse
from rest_framework.views import APIView, View
from django.utils import timezone
from datetime import timedelta
import json
import requests

from hello_world_project.settings import openai_client, tools, weather_api


from .models import User, TelegramMessage
from .serializers import LoginSerializer, RegisterSerializer, TelegramMessageSerializer, UserCheckSerializer

def get_weather(location):
    url = "http://api.weatherapi.com/v1/current.json"

    params = {
        "key": weather_api,
        "q": location
    }

    res = requests.get(url, params=params)
    data = res.json()

    return str(data["current"]["temp_c"]) + "°C"

class check_user(APIView):
    permission_classes = [AllowAny]
    
    def post(self, request):
        serializer = UserCheckSerializer(data=request.data)
        if not serializer.is_valid():
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

        tg_login = serializer.validated_data['tg_login']

        if User.objects.filter(tg_login=tg_login).exists():
            return Response(
                {'exists': True},
                status=409,
            )
        
        return Response(
            {"exists": False},
            status=404,
        )


class TelegramMessageViewSet(viewsets.ModelViewSet):
    serializer_class = TelegramMessageSerializer
    permission_classes = [IsAuthenticated]
    # permission_classes = [AllowAny]

    def get_queryset(self):
        return TelegramMessage.objects.filter(user=self.request.user.tg_login)
    
    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        
        user = request.user
        # user = User.objects.get(tg_login=serializer.validated_data["tg_login"])
        
        one_hour_ago = timezone.now() - timedelta(hours=1)
        
        history = TelegramMessage.objects.filter(
            tg_login=user,
            created_at__gte=one_hour_ago
        ).order_by("created_at")
        
        messages = []
        for msg in history:
            messages.append({
                "role": "user",
                "content": msg.user_text
            })
            if msg.chatbot_respond:
                messages.append({
                    "role": "assistant",
                    "content": msg.chatbot_respond
                })
        
        user_text = serializer.validated_data["user_text"]
        messages.append({
            "role": "user",
            "content": user_text
        })
        
        response = openai_client.responses.create(
            model="gpt-5.5",
            tools=tools,
            input=messages,
        )
        messages += response.output
        
        for item in response.output:
            if item.type == "function_call":
                if item.name == "get_weather":
                    location = json.loads(item.arguments)["location"]
                    weather = get_weather(location)
                    
                    messages.append({
                        "type": "function_call_output",
                        "call_id": item.call_id,
                        "output": weather,
                    })

        # print("\nChatGPT\n",response.output_text,"\n\n")
        
        response = openai_client.responses.create(
            model="gpt-5.5",
            instructions="Respond only with a weather generated by a tool.",
            tools=tools,
            input=messages,
        )
        
        TelegramMessage.objects.create(
            tg_login=user,
            user_text=serializer.validated_data["user_text"],
            chatbot_respond=response.output_text
        )

        return Response(
            {
                "ok": True,
                "output": response.output_text
            },
            status=201
        )

    
class RegisterView(APIView):
    permission_classes = [AllowAny]
    
    def post(self, request):
        serializer = RegisterSerializer(data=request.data)
        if not serializer.is_valid():
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

        tg_login = serializer.validated_data['tg_login']
        password = serializer.validated_data['password']

        user = User.objects.create_user(tg_login=tg_login, password=password)
        token, _ = Token.objects.get_or_create(user=user)
        return Response(
            {'token': token.key, 'user_id': user.id}, 
            status=status.HTTP_201_CREATED
        )


class LoginView(APIView):
    permission_classes = [AllowAny]
    
    def post(self, request):
        serializer = LoginSerializer(data=request.data)
        if not serializer.is_valid():
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

        identifier = serializer.validated_data['identifier']
        password = serializer.validated_data['password']

        user = authenticate(request, identifier=identifier, password=password)

        if user is None:
            return Response(
                {'error': 'Invalid credentials'},
                status=status.HTTP_401_UNAUTHORIZED
            )

        token, _ = Token.objects.get_or_create(user=user)
        return Response({
            'token': token.key,
            'user_id': user.id,
        })


class HelloWorldView(APIView):
    def get(self, request):
        return Response({
            'message': 'Hello, World!',
            'user': str(request.user),
        })
